#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
. ../../AllwmakeFunctions

#------------------------------------------------------------------------------

wmakeStatus -all $targetType populationBalance
wmakeStatus -all $targetType mixing
runScriptStatus compressible/Allwmake $targetType $*
wmakeStatus -all $targetType velocityDistributionTransport
wmakeStatus -all $targetType multiphase

reportStatus

#------------------------------------------------------------------------------
