#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------

wmake -all $targetType populationBalance
wmake -all $targetType mixing
compressible/Allwmake
wmake -all $targetType velocityDistributionTransport
wmake -all $targetType multiphase


#------------------------------------------------------------------------------
