#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

# wmake conditionalMomentInversion
wmake eigenSolver
wmake populationBalanceModel
wmake univariateQuadratureApproximation
wmake Vandermonde
wmake univariateMomentAdvection/setMoments1D
wmake univariateMomentAdvection/setMoments2D

wmake -all momentInversions/univariate
wmake momentInversions/multivariate/monoKineticMomentInversion
wmake momentInversions/multivariate/CHyQMOMMomentInversion
wmake momentInversions/multivariate/sizeCHyQMOMMomentInversion
wmake momentInversions/multivariate/TensorProductMomentInversion
# conditional moment inversion needs to be updated for new structure

#------------------------------------------------------------------------------
