#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# wmake conditionalMomentInversion
wmake libso eigenSolver
wmake libso populationBalanceModel
wmake libso univariateQuadratureApproximation
wmake libso Vandermonde
wmake libso univariateMomentAdvection/setMoments1D
wmake libso univariateMomentAdvection/setMoments2D

wmake -all momentInversions/univariate
wmake libso momentInversions/multivariate/monoKineticMomentInversion
wmake libso momentInversions/multivariate/CHyQMOMMomentInversion
wmake libso momentInversions/multivariate/sizeCHyQMOMMomentInversion
wmake libso momentInversions/multivariate/TensortProductMomentInversion
# conditional moment inversion needs to be updated for new structure

#------------------------------------------------------------------------------
