#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------
# Use build from FOAM_MODULE_* (defaults to user locations)

wmake Vandermonde
wmake -all momentSets/univariate
wmake -all momentInversions/univariate

# conditional moment inversion needs to be updated for new structure
# wmake conditionalMomentInversion
wmake momentInversions/multivariate/monoKineticMomentInversion
wmake momentInversions/multivariate/CHyQMOMMomentInversion
wmake momentInversions/multivariate/sizeCHyQMOMMomentInversion
wmake momentInversions/multivariate/TensorProductMomentInversion

wmake populationBalanceModel
wmake univariateQuadratureApproximation
wmake univariateMomentAdvection/setMoments1D
wmake univariateMomentAdvection/setMoments2D

#------------------------------------------------------------------------------
