#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf postProcessing
rm -f validation/*.eps
rm -f validation/log.*

# ----------------------------------------------------------------- end-of-file
