# Travis CI setup for OpenQBMM

sudo: required
dist: trusty
language: cpp

env:
    # Test with OpenFOAM 4 only
    - OF_VERS=4

before_install:
    - sudo add-apt-repository http://dl.openfoam.org/ubuntu
    - sudo sh -c "wget -O - http://dl.openfoam.org/gpg.key | apt-key add -"
    - sudo apt-get update -qq
    - sudo apt-get install -qq openfoam${OF_VERS}
    - sudo apt-get install -qq vera++

install:
    - source /opt/openfoam${OF_VERS}/etc/bashrc
    - ./Allwmake

before_script:
    - source /opt/openfoam${OF_VERS}/etc/bashrc

script:
    # Should add an automated test runner script here
    # - ./Alltest
    - ./foamStyleCheck/checkStyle
