#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

(cd src && ./Allwmake)

wmake -all applications

curl -A "OpenQBMM" http://bit.ly/openqbmm-dev

# ----------------------------------------------------------------- end-of-file
