#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------

wclean all src
wclean all applications
wclean all test

#------------------------------------------------------------------------------
