#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf 0/alpha.air
rm -rf 0/moment.*
rm -rf postProcessing
rm -f validation/*.eps

# ----------------------------------------------------------------- end-of-file
