#!/bin/sh
cd "${0%/*}" || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Generate mesh
runApplication blockMesh

# Decompose the mesh for parallel computation
runApplication decomposePar

# Run the solver in parallel
runParallel $(getApplication)

# Reconstruct the parallel results
runApplication reconstructPar

#------------------------------------------------------------------------------
