#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf processor*
rm -rf 0/alpha.air
rm -rf 0/moment.*
rm -rf log.*

# ----------------------------------------------------------------- end-of-file
