#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# The initial volume fraction is copied from its .orig by Allrun
rm -f 0/alpha.particles

# ----------------------------------------------------------------- end-of-file
