#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions

org="0"
const="constant"
system="system"
dyn="dynamicCode"
animation="animation"
data="data"


for f in *
do
    if [ -d $f ]; then
        if                              \
            [ $f != $org ]              \
         && [ $f != $const ]            \
         && [ $f != $system ]           \
         && [ $f != $animation ]        \
         && [ $f != $data ]             \
         && [ $f != $dyn ] ; then
            rm -r $f
        fi
    fi
done

# The initial volume fraction is the field setFields works on, so it has to
# be in place before it runs
cp 0/alpha.particles.orig 0/alpha.particles

blockMesh
setFields
decomposePar
mpirun -np 3 denseAGFoam -parallel
