#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir 0 2>&1
cp 0.org/* 0/ 2>&1

runApplication blockMesh
runApplication generateMoments
runApplication setFields

runApplication decomposePar -time 0
runParallel twoPhaseEulerFoam 4

runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
