#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions

org="0.org"
const="constant"
system="system"
dyn="dynamicCode"


for f in *
do
    if [ -d $f ]; then
        if                              \
            [ $f != $org ]              \
         && [ $f != $const ]            \
         && [ $f != $system ]           \
         && [ $f != $dyn ] ; then
            rm -r $f
        fi
    fi
done

mkdir 0
cp 0.org/* 0/
setFields
decomposePar
mpirun -np 4 twoPhaseEulerFoam -parallel
