#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir 0
cp 0.org/* 0/

runApplication generateMoments
runApplication setFields
runApplication decomposePar
runParallel polydisperseBubbleFoam
