#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../AllrunFunctions

runStep blockMesh
runStep decomposePar 
runStepParallel compressiblePbeTransportFoam
runStep reconstructPar
