#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../AllrunFunctions

validationCases="case5 case6 case7 case8 case9"

for caseName in $validationCases
do
    runCase $caseName
done

reportCases

# ----------------------------------------------------------------- end-of-file
