#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../AllrunFunctions

validationCases="case1 case2 case3 case4 case5"

for caseName in $validationCases
do
    runCase $caseName
done

reportCases

# ----------------------------------------------------------------- end-of-file
