#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
. ../../../AllwmakeFunctions
#------------------------------------------------------------------------------

wmakeLnIncludeStatus interfacialModels

wmakeStatus $targetType twoPhaseSystem
wmakeStatus $targetType interfacialModels
wmakeStatus $targetType phaseCompressibleTurbulenceModels
wmakeStatus $targetType polydisperseBubbleFoam
wmakeStatus $targetType denseAGFoam

reportStatus

#------------------------------------------------------------------------------
