#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../AllrunFunctions

# Get application directory
application=`getApplication`

runStep blockMesh

runStep $application

# ----------------------------------------------------------------- end-of-file
