#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0 > /dev/null 2>&1

cleanCase
rm -rf system/controlDict
rm -rf postProcessing
rm -f validation/*.eps
rm -f validation/volumeAveragedD43.dat

# ----------------------------------------------------------------- end-of-file
