#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../AllrunFunctions

runStep blockMesh
runStep generateMoments
runStep decomposePar

runStepParallel oneWayCoupledVdfTransportFoam

runStep reconstructPar -latestTime

( cd validation && ./createGraphs )

# ----------------------------------------------------------------- end-of-file
