#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf postProcessing
rm -rf 
rm -rf 0.*
rm -rf log.*

# ----------------------------------------------------------------- end-of-file
