#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
foamListTimes -rm

rm -r 0
mkdir 0
cp 0.org/* 0/

# setFields
denseAGFoam
# decomposePar
# mpirun -np 4 denseAGFoam -parallel
