#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../../AllrunFunctions

# Set application name
application=`getApplication`

runStep blockMesh
runStep generateMoments
runStep $application

( cd validation && ./createGraphs )

# ----------------------------------------------------------------- end-of-file
