#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="case5 case6 case7 case8 case9"

for caseName in $keepCases
do
(
    (cd $caseName && ./Allclean)
)
done

# ----------------------------------------------------------------- end-of-file
