#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
. ../../../../AllwmakeFunctions
#------------------------------------------------------------------------------

wmakeStatus $targetType compressibleSystem

wmakeStatus
wmakeStatus $targetType compressiblePbeTransportFoam

reportStatus

#------------------------------------------------------------------------------
