#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso compressibleSystem
wclean
wclean compressiblePbeTransportFoam

#------------------------------------------------------------------------------
