#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir 0
cp 0.org/* 0/

runApplication blockMesh
runApplication generateMoments
runApplication setFields
runApplication decomposePar
runParallel polydisperseBubbleFoam

# NOTE: This case is very unstable and typically needs to be restarted several time. The createGraph program will read all of the pProbes folders and create the total list of pressures
# To restart run:
# mpirun -np $numberOfProcessors polydisperseBubbleFoam -parallel
