#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

validationCases="case1 case2 case3 case4 case5"

for caseName in $validationCases
do
    echo Running $caseName

    ( cd $caseName && ./Allrun )
done

# ----------------------------------------------------------------- end-of-file
