#!/bin/bash
#
# read d43average from pbeTransportFoam
createEpsTotalMass()
{

    gnuplot<<EOF

    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "monoModal_nonLinearEvaporation_totalMass.eps"
    set xlabel "X-position [m]"
    set ylabel "Mass Density [g/cm^3]"
    set grid
    set key right top
    set size 2,2
    set xrange [0.1:0.25]
    set yrange [0:0.004]

    plot    "$1" using 1:2 title 'DQMOM without flux (Fox 2008)'\
                with points pointtype 7 ps 3 linecolor rgb 'black',\
            "$2" using 1:2 title 'DQMOM with flux (Fox 2008)'\
                with points pointtype 5 ps 3 linecolor rgb 'blue',\
            "$3" using 1:(\$2*633/1000) title 'OpenQBMM' \
                with line lt 2 linewidth 5 linecolor rgb '#9db668'
EOF
}
createEpsUr()
{

    gnuplot<<EOF

    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "monoModal_nonLinearEvaporation_Ur.eps"
    set xlabel "X-position [m]"
    set ylabel "Relative Velocity Magnitude [m/s]"
    set grid
    set key right top
    set size 2,2
    set xrange [0.1:0.25]
    set yrange [0:0.6]

    plot    "$1" using 1:2 title 'DQMOM without flux (Fox 2008)'\
                with points pointtype 7 ps 3 linecolor rgb 'black',\
            "$2" using 1:2 title 'DQMOM with flux (Fox 2008)'\
                with points pointtype 5 ps 3 linecolor rgb 'blue',\
            "$3" using 1:(((\$2 - \$5)**2 + (\$3 - \$6)**2)**0.5) title 'OpenQBMM' \
                with line lt 2 linewidth 5 linecolor rgb '#9db668'
EOF
}
# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

# extract data from log file and put them in a text file for gnuplot
# cat ../log.oneWayCoupledVdfTransportFoam | grep '^Time = ' | cut -c8-15 > time.tmp
# cat ../log.oneWayCoupledVdfTransportFoam | grep 'Volume averaged normalized d10' | cut -d':' -f2 > d10.tmp
# paste time.tmp d10.tmp > volumeAveragedD10.dat

#Remove temporary files
# rm time.tmp d10.tmp

# paths to data
VALIDATIONDATAROOT=./validationData
time=$(cd ../ && foamListTimes -latestTime)

echo "    processing profiles" > log.createGraphs 2>&1
OPENQBMMM_mass="../postProcessing/sampleDict/$time/Centerline_alpha*"
OPENQBMMM_U="../postProcessing/sampleDict/$time/Centerline_U*"
VALIDATION_mass="$VALIDATIONDATAROOT/Fox_totalMass.csv"
VALIDATION_massFlux="$VALIDATIONDATAROOT/Fox_totalMass_flux.csv"
VALIDATION_Ur="$VALIDATIONDATAROOT/Fox_Ur.csv"
VALIDATION_UrFlux="$VALIDATIONDATAROOT/Fox_Ur_flux.csv"

createEpsTotalMass $VALIDATION_mass $VALIDATION_massFlux $OPENQBMMM_mass
createEpsUr $VALIDATION_Ur $VALIDATION_UrFlux $OPENQBMMM_U

epstopdf *totalMass.eps
epstopdf *Ur.eps

echo Done
