#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

wmake $targetType phaseModel
wmake $targetType interfacialModels
wmake $targetType phaseCompressibleTurbulenceModels
wmake $targetType vdfTransportFoam
wmake $targetType oneWayCoupledVdfTransportFoam
wmake $targetType diluteVdfTransportFoam

#------------------------------------------------------------------------------
