#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
#------------------------------------------------------------------------------

wclean libso phaseModel
wclean libso interfacialModels
wclean libso phaseCompressibleTurbulenceModels
wclean libso vdfTransportFoam
wclean libso diluteVdfTransportFoam

#------------------------------------------------------------------------------
