#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
. ../../../AllwmakeFunctions
#------------------------------------------------------------------------------

wmakeStatus $targetType phaseModel
wmakeStatus $targetType interfacialModels
wmakeStatus $targetType phaseCompressibleTurbulenceModels
wmakeStatus $targetType vdfTransportFoam
wmakeStatus $targetType oneWayCoupledVdfTransportFoam
wmakeStatus $targetType diluteVdfTransportFoam

reportStatus

#------------------------------------------------------------------------------
