OpenQBMM: quadratureNode< weightType, abscissaType > Class Template Reference
quadratureNode< weightType, abscissaType > Class Template Reference
Stores a quadrature weight and a quadrature abscissa, whose type is templated.
Classes
class iNew
Return a pointer to a new quadrature node created on freestore.
Public Member Functions
quadratureNode (const word &name, const dictionary &nodeDict, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions, const wordList &boundaryTypes)
Construct from name, dictionary, mesh and dimensions.
quadratureNode (const word &name, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions)
Construct from name, mesh and dimensions.
autoPtr< quadratureNode
< weightType, abscissaType > > clone () const
Return clone.
virtual ~quadratureNode ()
Destructor.
const word & name () const
Return the name of the node.
bool extended () const
label nSecondaryNodes () const
Returns the number of secondary nodes.
const weightType & primaryWeight () const
Const access to the weight of the node.
weightType & primaryWeight ()
Non-const access to the weight of the node.
const abscissaType & primaryAbscissa () const
Const access to the abscissa of the node.
abscissaType & primaryAbscissa ()
Non-const access to the abscissa of the node.
const PtrList< weightType > & secondaryWeights () const
Const access to the secondary weight of the node.
PtrList< weightType > & secondaryWeights ()
Non-const access to the secondary weight of the node.
const PtrList< abscissaType > & secondaryAbscissae () const
Const access to the list of secondary abscissae of the node.
PtrList< abscissaType > & secondaryAbscissae ()
Non-const access to the list of secondary abscissae of the node.
Detailed Description
template<class weightType, class abscissaType>
class Foam::quadratureNode< weightType, abscissaType >
Stores a quadrature weight and a quadrature abscissa, whose type is templated.
Source files
quadratureNode.H
quadratureNode.C
quadratureNodeI.H
Definition at line 61 of file quadratureNode.H.
Constructor & Destructor Documentation
quadratureNode (const word & name, const dictionary & nodeDict, const fvMesh & mesh, const dimensionSet & weightDimensions, const dimensionSet & abscissaDimensions, const wordList & boundaryTypes)
Construct from name, dictionary, mesh and dimensions.
Definition at line 85 of file quadratureNode.C.
quadratureNode (const word & name, const fvMesh & mesh, const dimensionSet & weightDimensions, const dimensionSet & abscissaDimensions)
Construct from name, mesh and dimensions.
Definition at line 35 of file quadratureNode.C.
~quadratureNode () virtual
Destructor.
Definition at line 140 of file quadratureNode.C.
Member Function Documentation
Foam::autoPtr< Foam::quadratureNode< weightType, abscissaType > > clone () const
Return clone.
Definition at line 147 of file quadratureNode.C.
const Foam::word & name () const inline
Return the name of the node.
Definition at line 32 of file quadratureNodeI.H.
bool extended () const inline
Definition at line 38 of file quadratureNodeI.H.
Foam::label nSecondaryNodes () const inline
Returns the number of secondary nodes.
Definition at line 45 of file quadratureNodeI.H.
const weightType & primaryWeight () const inline
Const access to the weight of the node.
Definition at line 53 of file quadratureNodeI.H.
Referenced by univariateQuadratureApproximation::interpolateNodes(), univariateQuadratureApproximation::updateBoundaryQuadrature(), and univariateQuadratureApproximation::updateQuadrature().
weightType & primaryWeight () inline
Non-const access to the weight of the node.
Definition at line 59 of file quadratureNodeI.H.
const abscissaType & primaryAbscissa () const inline
Const access to the abscissa of the node.
Definition at line 66 of file quadratureNodeI.H.
Referenced by univariateQuadratureApproximation::interpolateNodes(), univariateQuadratureApproximation::updateBoundaryQuadrature(), and univariateQuadratureApproximation::updateQuadrature().
abscissaType & primaryAbscissa () inline
Non-const access to the abscissa of the node.
Definition at line 72 of file quadratureNodeI.H.
const Foam::PtrList< weightType > & secondaryWeights () const inline
Const access to the secondary weight of the node.
Definition at line 79 of file quadratureNodeI.H.
Foam::PtrList< weightType > & secondaryWeights () inline
Non-const access to the secondary weight of the node.
Definition at line 87 of file quadratureNodeI.H.
const Foam::PtrList< abscissaType > & secondaryAbscissae () const inline
Const access to the list of secondary abscissae of the node.
Definition at line 95 of file quadratureNodeI.H.
Foam::PtrList< abscissaType > & secondaryAbscissae () inline
Non-const access to the list of secondary abscissae of the node.
Definition at line 103 of file quadratureNodeI.H.
The documentation for this class was generated from the following files:
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureNode/quadratureNode.H
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureNode/quadratureNode.C
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureNode/quadratureNodeI.H