#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

keepCases="\
GQMOM/condensationLage \
GQMOM/diffusionControlledGrowthMcGraw \
madadiPassalacquaGQMOMGamma \
madadiPassalacquaGQMOMLognormal \
madadiPassalacquaQMOM \
madadiPassalacquaRadau \
momentConvergence/GQMOM \
momentConvergence/QMOM \
"

for caseName in $keepCases
do
(
    (cd $caseName && ./Allclean)
)
done

# ----------------------------------------------------------------- end-of-file
