#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../AllrunFunctions

validationCases="\
GQMOM/condensationLage \
GQMOM/diffusionControlledGrowthMcGraw \
madadiPassalacquaGQMOMGamma \
madadiPassalacquaGQMOMLognormal \
madadiPassalacquaQMOM \
madadiPassalacquaRadau \
momentConvergence/GQMOM \
momentConvergence/QMOM \
"

for caseName in $validationCases
do
    runCase $caseName
done

reportCases

# ----------------------------------------------------------------- end-of-file
