OpenQBMM: extendedQuadratureNode< weightType, abscissaType, sigmaType > Class Template Reference
extendedQuadratureNode< weightType, abscissaType, sigmaType > Class Template Reference
Extended version of the quadrature node, which stores the list of secondary weights and abscissae associated to the primary weight and abscissa, and the sigma parameter.
Classes
class iNew
Return a pointer to a new quadrature node created on freestore.
Public Member Functions
extendedQuadratureNode (const word &name, const dictionary &nodeDict, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions, const wordList &boundaryTypes)
Construct from name, dictionary, mesh and dimensions.
extendedQuadratureNode (const word &name, const label nSecondaryNodes, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions)
Construct from name, number of secondary nodes, mesh and dimensions.
autoPtr
< extendedQuadratureNode
< weightType, abscissaType,
sigmaType > > clone () const
Return clone.
virtual ~extendedQuadratureNode ()
Destructor.
const word & name () const
Return the name of the node.
bool extended () const
label nSecondaryNodes () const
Returns the number of secondary nodes.
const PtrList< weightType > & secondaryWeights () const
Const access to the secondary weights of the node.
PtrList< weightType > & secondaryWeights ()
Non-const access to the secondary weights of the node.
const PtrList< abscissaType > & secondaryAbscissae () const
Const access to the list of secondary abscissae of the node.
PtrList< abscissaType > & secondaryAbscissae ()
Non-const access to the list of secondary abscissae of the node.
const sigmaType & sigma () const
Const access to sigma.
sigmaType & sigma ()
Non-const access to sigma.
Public Member Functions inherited from quadratureNode< weightType, abscissaType >
quadratureNode (const word &name, const dictionary &nodeDict, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions, const wordList &boundaryTypes)
Construct from name, dictionary, mesh and dimensions.
quadratureNode (const word &name, const fvMesh &mesh, const dimensionSet &weightDimensions, const dimensionSet &abscissaDimensions)
Construct from name, mesh and dimensions.
autoPtr< quadratureNode
< weightType, abscissaType > > clone () const
Return clone.
virtual ~quadratureNode ()
Destructor.
const word & name () const
Return the name of the node.
bool extended () const
label nSecondaryNodes () const
Returns the number of secondary nodes.
const weightType & primaryWeight () const
Const access to the weight of the node.
weightType & primaryWeight ()
Non-const access to the weight of the node.
const abscissaType & primaryAbscissa () const
Const access to the abscissa of the node.
abscissaType & primaryAbscissa ()
Non-const access to the abscissa of the node.
const PtrList< weightType > & secondaryWeights () const
Const access to the secondary weight of the node.
PtrList< weightType > & secondaryWeights ()
Non-const access to the secondary weight of the node.
const PtrList< abscissaType > & secondaryAbscissae () const
Const access to the list of secondary abscissae of the node.
PtrList< abscissaType > & secondaryAbscissae ()
Non-const access to the list of secondary abscissae of the node.
Detailed Description
template<class weightType, class abscissaType, class sigmaType>
class Foam::extendedQuadratureNode< weightType, abscissaType, sigmaType >
Extended version of the quadrature node, which stores the list of secondary weights and abscissae associated to the primary weight and abscissa, and the sigma parameter.
Source files
extendedQuadratureNode.H
extendedQuadratureNode.C
extendedQuadratureNodeI.H
Definition at line 55 of file extendedQuadratureNode.H.
Constructor & Destructor Documentation
extendedQuadratureNode (const word & name, const dictionary & nodeDict, const fvMesh & mesh, const dimensionSet & weightDimensions, const dimensionSet & abscissaDimensions, const wordList & boundaryTypes)
Construct from name, dictionary, mesh and dimensions.
Definition at line 133 of file extendedQuadratureNode.C.
extendedQuadratureNode (const word & name, const label nSecondaryNodes, const fvMesh & mesh, const dimensionSet & weightDimensions, const dimensionSet & abscissaDimensions)
Construct from name, number of secondary nodes, mesh and dimensions.
Definition at line 32 of file extendedQuadratureNode.C.
~extendedQuadratureNode () virtual
Destructor.
Definition at line 243 of file extendedQuadratureNode.C.
Member Function Documentation
Foam::autoPtr< Foam::extendedQuadratureNode< weightType, abscissaType, sigmaType > > clone () const
Return clone.
Definition at line 253 of file extendedQuadratureNode.C.
const Foam::word & name () const inline
Return the name of the node.
Definition at line 29 of file extendedQuadratureNodeI.H.
Referenced by univariateQuadratureApproximation::univariateQuadratureApproximation().
bool extended () const inline
Definition at line 36 of file extendedQuadratureNodeI.H.
Foam::label nSecondaryNodes () const inline
Returns the number of secondary nodes.
Definition at line 44 of file extendedQuadratureNodeI.H.
const Foam::PtrList< weightType > & secondaryWeights () const inline
Const access to the secondary weights of the node.
Definition at line 52 of file extendedQuadratureNodeI.H.
Referenced by univariateQuadratureApproximation::interpolateNodes(), univariateQuadratureApproximation::updateBoundaryQuadrature(), and univariateQuadratureApproximation::updateQuadrature().
Foam::PtrList< weightType > & secondaryWeights () inline
Non-const access to the secondary weights of the node.
Definition at line 60 of file extendedQuadratureNodeI.H.
const Foam::PtrList< abscissaType > & secondaryAbscissae () const inline
Const access to the list of secondary abscissae of the node.
Definition at line 68 of file extendedQuadratureNodeI.H.
Referenced by univariateQuadratureApproximation::interpolateNodes(), univariateQuadratureApproximation::univariateQuadratureApproximation(), univariateQuadratureApproximation::updateBoundaryQuadrature(), and univariateQuadratureApproximation::updateQuadrature().
Foam::PtrList< abscissaType > & secondaryAbscissae () inline
Non-const access to the list of secondary abscissae of the node.
Definition at line 76 of file extendedQuadratureNodeI.H.
const sigmaType & sigma () const inline
Const access to sigma.
Definition at line 84 of file extendedQuadratureNodeI.H.
Referenced by univariateQuadratureApproximation::interpolateNodes(), univariateQuadratureApproximation::updateBoundaryQuadrature(), and univariateQuadratureApproximation::updateQuadrature().
sigmaType & sigma () inline
Non-const access to sigma.
Definition at line 91 of file extendedQuadratureNodeI.H.
The documentation for this class was generated from the following files:
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureNode/extendedQuadratureNode.H
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureNode/extendedQuadratureNode.C
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureNode/extendedQuadratureNodeI.H