#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -rf 0.orig 0

# Set application name
application=`getApplication`

runApplication blockMesh
runApplication setMoments2D
runApplication $application

# ----------------------------------------------------------------- end-of-file
