OpenQBMM: univariateQuadratureApproximation Class Reference
univariateQuadratureApproximation Class Reference
Provides storage for the moments and the corresponding quadrature approximation of a univariate distribution function. Methods to update the moments and the quadrature approximation are provided.
Public Member Functions
univariateQuadratureApproximation (const fvMesh &mesh)
Calculate the m1/m0 ratio.
virtual ~univariateQuadratureApproximation ()
Destructor.
const PtrList
< extendedVolScalarNode > & nodes () const
Return the nodes.
const momentFieldSet
< volUnivariateMoment,
extendedVolScalarNode > & moments () const
Const access to the moments.
momentFieldSet
< volUnivariateMoment,
extendedVolScalarNode > & moments ()
Non-const access to the moments.
const momentFieldSet
< surfaceUnivariateMoment,
extendedSurfaceScalarNode > & momentsNei () const
Const access to the interpolated moments (neighbour)
momentFieldSet
< surfaceUnivariateMoment,
extendedSurfaceScalarNode > & momentsNei ()
Non-const access to the interpolated moments (neighbour)
const momentFieldSet
< surfaceUnivariateMoment,
extendedSurfaceScalarNode > & momentsOwn () const
Const access to the interpolated moments (owner)
momentFieldSet
< surfaceUnivariateMoment,
extendedSurfaceScalarNode > & momentsOwn ()
Non-const access to the interpolated moments (owner)
label nDimensions () const
Return the number of dimensions in the distribution.
label nMoments () const
Return the number of moments.
void interpolateNodes ()
Interpolate nodes.
void updateBoundaryQuadrature ()
Update quadrature nodes on fixed-value boundaries.
void updateQuadrature ()
Recalculate the quadrature nodes from the moments.
void updateMoments ()
Recalculate the moments from the quadrature nodes.
Detailed Description
Provides storage for the moments and the corresponding quadrature approximation of a univariate distribution function. Methods to update the moments and the quadrature approximation are provided.
Source files
univariateQuadratureApproximation.H
univariateQuadratureApproximation.C
univariateQuadratureApproximationI.H
Definition at line 62 of file univariateQuadratureApproximation.H.
Constructor & Destructor Documentation
univariateQuadratureApproximation (const fvMesh & mesh) explicit
Calculate the m1/m0 ratio.
tmp<volScalarField> m1ByM0();Construct from mesh
Definition at line 34 of file univariateQuadratureApproximation.C.
References extendedQuadratureNode< weightType, abscissaType, sigmaType >::name(), extendedMomentInversion::New(), and extendedQuadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae().
~univariateQuadratureApproximation () virtual
Destructor.
Definition at line 203 of file univariateQuadratureApproximation.C.
Member Function Documentation
const Foam::PtrList< Foam::extendedVolScalarNode > & nodes () const inline
Return the nodes.
Definition at line 29 of file univariateQuadratureApproximationI.H.
const Foam::momentFieldSet< Foam::volUnivariateMoment, Foam::extendedVolScalarNode > & moments () const inline
Const access to the moments.
Definition at line 35 of file univariateQuadratureApproximationI.H.
Foam::momentFieldSet< Foam::volUnivariateMoment, Foam::extendedVolScalarNode > & moments () inline
Non-const access to the moments.
Definition at line 41 of file univariateQuadratureApproximationI.H.
const Foam::momentFieldSet< Foam::surfaceUnivariateMoment, Foam::extendedSurfaceScalarNode > & momentsNei () const inline
Const access to the interpolated moments (neighbour)
Definition at line 50 of file univariateQuadratureApproximationI.H.
Foam::momentFieldSet< Foam::surfaceUnivariateMoment, Foam::extendedSurfaceScalarNode > & momentsNei () inline
Non-const access to the interpolated moments (neighbour)
Definition at line 59 of file univariateQuadratureApproximationI.H.
const Foam::momentFieldSet< Foam::surfaceUnivariateMoment, Foam::extendedSurfaceScalarNode > & momentsOwn () const inline
Const access to the interpolated moments (owner)
Definition at line 68 of file univariateQuadratureApproximationI.H.
Foam::momentFieldSet< Foam::surfaceUnivariateMoment, Foam::extendedSurfaceScalarNode > & momentsOwn () inline
Non-const access to the interpolated moments (owner)
Definition at line 77 of file univariateQuadratureApproximationI.H.
Foam::label nDimensions () const inline
Return the number of dimensions in the distribution.
Definition at line 82 of file univariateQuadratureApproximationI.H.
Foam::label nMoments () const inline
Return the number of moments.
Definition at line 87 of file univariateQuadratureApproximationI.H.
void interpolateNodes ()
Interpolate nodes.
Definition at line 209 of file univariateQuadratureApproximation.C.
References quadratureNode< weightType, abscissaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType >::primaryWeight(), extendedQuadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae(), extendedQuadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights(), and extendedQuadratureNode< weightType, abscissaType, sigmaType >::sigma().
void updateBoundaryQuadrature ()
Update quadrature nodes on fixed-value boundaries.
Definition at line 322 of file univariateQuadratureApproximation.C.
References univariateMomentSet::invert(), quadratureNode< weightType, abscissaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType >::primaryWeight(), extendedQuadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae(), extendedQuadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights(), and extendedQuadratureNode< weightType, abscissaType, sigmaType >::sigma().
void updateQuadrature ()
Recalculate the quadrature nodes from the moments.
Definition at line 377 of file univariateQuadratureApproximation.C.
References univariateMomentSet::invert(), quadratureNode< weightType, abscissaType >::primaryAbscissa(), quadratureNode< weightType, abscissaType >::primaryWeight(), extendedQuadratureNode< weightType, abscissaType, sigmaType >::secondaryAbscissae(), extendedQuadratureNode< weightType, abscissaType, sigmaType >::secondaryWeights(), and extendedQuadratureNode< weightType, abscissaType, sigmaType >::sigma().
void updateMoments ()
Recalculate the moments from the quadrature nodes.
Definition at line 459 of file univariateQuadratureApproximation.C.
The documentation for this class was generated from the following files:
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureApproximation/univariateQuadratureApproximation/univariateQuadratureApproximation.H
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureApproximation/univariateQuadratureApproximation/univariateQuadratureApproximation.C
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/quadratureApproximation/univariateQuadratureApproximation/univariateQuadratureApproximationI.H