#!/bin/bash
#
#Read d43average from pbeTransportFoam for 75 rpm
createEps()
{
    gnuplot<<EOF
    stats "$1" using 4 name "C" noout

    set terminal postscript eps enhanced color font 'Helvetica,60' linewidth 2\
        dl 8.0
    set output "Diaz3_2_4_p.eps"
    set xlabel "Time [s]"
    set ylabel "Normalized Pressure"
    set datafile commentschars "#"
    set grid
    set key off
    set size 2,2
    set autoscale
    set xrange [0:50]
    set yrange [-20:20]
    set key left top Left box

    plot    "$2" using 1:2 title 'Diaz'\
                with points pointtype 7 ps 2 linecolor rgb 'black', \
            "$1" using (\$1 - $3):(\$4-C_mean) every 250 title 'QBMM'\
                with lines linetype 1 linewidth 2 linecolor rgb '#9db668'
EOF
}

# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

time=50
echo $1
if [ $1 ];
then
    time=$1
fi

#set case Direcory names
pProbesDir="../postProcessing/pProbes"

#Set files
pProbes_modified="$pProbesDir/0/p_modified"
touch $pProbes_modified
exp="experiments_2_4.data"

printf "Times included:\n"
for d in $(ls $pProbesDir | sort -g);
do
    printf "\t$d\n"
    if [ $d = "0" ];
    then
        cat "$pProbesDir/$d/p" > $pProbes_modified
    else
        cat "$pProbesDir/$d/p">> $pProbes_modified
    fi
done

pProbesTmp="$pProbesDir/0/p_rghTmp"
pProbesFinal="$pProbesDir/0/p_rghFinal"

begin=$( grep -wn -m1 "$time" $pProbes_modified | awk '{ print $1 }' | sed 's/:/ /' )
tail -n +$begin $pProbes_modified >$pProbesTmp

endTime=$(($time+50))
end=$( grep -wn -m1 "$endTime" $pProbesTmp | awk '{ print $1 }' | sed 's/:/ /' )
head -n $end $pProbesTmp >$pProbesFinal

rm $pProbesTmp
createEps $pProbesFinal $exp $time

printf "\nDone\n"
