#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso eigenSolver
wclean libso Vandermonde
wclean libso quadratureMethods/momentSets
wclean libso quadratureMethods/momentInversion/univariate/basic
wclean libso quadratureMethods/momentInversion/univariate/extended
wclean libso quadratureMethods/momentInversion/multivariate/conditional
wclean libso quadratureMethods/quadratureApproximation
wclean libso quadratureMethods/PDFTransportModels
wclean libso quadratureMethods/populationBalanceModels
wclean libso quadratureMethods/mixingModels

# ----------------------------------------------------------------- end-of-file
