#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments
. ../AllwmakeFunctions
#------------------------------------------------------------------------------

wmakeStatus libso Vandermonde
wmakeStatus libso quadratureMethods/momentSets
wmakeStatus libso quadratureMethods/momentInversion
wmakeStatus libso quadratureMethods/hermiteQuadrature
wmakeStatus libso quadratureMethods/quadratureNode
wmakeStatus libso quadratureMethods/fieldMomentInversion
wmakeStatus libso quadratureMethods/quadratureApproximations
wmakeStatus libso quadratureMethods/momentAdvection
wmakeStatus libso quadratureMethods/PDFTransportModels
wmakeStatus libso quadratureMethods/mixingModels
wmakeStatus libso quadratureMethods/populationBalanceModels

reportStatus

#------------------------------------------------------------------------------
