#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso eigenSolver
wclean libso quadratureMethods/univariateMomentSet

# ----------------------------------------------------------------- end-of-file
