#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmake libso eigenSolver
wmake libso Vandermonde
wmake libso quadratureMethods/momentSets
wmake libso quadratureMethods/momentInversion/
wmake libso quadratureMethods/hermiteQuadrature
wmake libso quadratureMethods/fieldMomentInversion
wmake libso quadratureMethods/quadratureApproximations
wmake libso quadratureMethods/momentAdvection
wmake libso quadratureMethods/PDFTransportModels
wmake libso quadratureMethods/mixingModels
wmake libso quadratureMethods/populationBalanceModels

# ----------------------------------------------------------------- end-of-file
