#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso eigenSolver
wclean libso quadratureMethods/univariateMomentSet
wclean libso quadratureMethods/extentedMomentInversion
wclean libso quadratureMethods/quadratureApproximation
wclean libso quadratureMethods/PDFTransportModels
wclean libso quadratureMethods/populationBalanceModels

# ----------------------------------------------------------------- end-of-file
