OpenQBMM: univariateMomentSet Class Reference
univariateMomentSet Class Reference
Stores and operates on a set of univariate moments.
Public Member Functions
univariateMomentSet (const label nMoments, const scalar initValue)
Construct from number of moments and initial value.
univariateMomentSet (const scalarDiagonalMatrix &m)
Construct from diagonalMatrix.
virtual ~univariateMomentSet ()
Destructor.
const scalarDiagonalMatrix & abscissae () const
Return quadrature abscissae.
void invert ()
Invert the set of moments to compute weights and abscissae.
void update ()
Update moments from weights and abscissae.
bool isInverted () const
Returns the status of inversion.
bool isRealizable ()
Return realizability status of the moment set.
label nInvertibleMoments ()
Return the number of invertible moments.
label nRealizableMoments ()
Return the number of realizable moments.
label nMoments () const
Return the number of moments.
label nNodes () const
Return the number of nodes.
const scalarDiagonalMatrix & weights () const
Return quadrature weights.
Detailed Description
Stores and operates on a set of univariate moments.
References
    "Modified moments and Gaussian quadratures"
    J C Wheeler
    Rocky Mountain Journal of Mathematics
    Volume 4, Pages 287-296, 1974
    "Numerical Recipes in C++"
    W H Press, S A Teukolsky, W Vetterling, B P Flannery
    Cambridge University Press, 2007
    "The theory of canonical moments with applications in Statistics,
    Probability and Analysis"
    H Dette, W. J. Studden
    Wiley & Sons, 1997
Source files
univariateMomentSet.H
univariateMomentSet.C
univariateMomentSetI.H
Definition at line 70 of file univariateMomentSet.H.
Constructor & Destructor Documentation
univariateMomentSet (const label nMoments, const scalar initValue)
Construct from number of moments and initial value.
Definition at line 33 of file univariateMomentSet.C.
univariateMomentSet (const scalarDiagonalMatrix & m)
Construct from diagonalMatrix.
Definition at line 48 of file univariateMomentSet.C.
~univariateMomentSet () virtual
Destructor.
Definition at line 64 of file univariateMomentSet.C.
Member Function Documentation
const Foam::scalarDiagonalMatrix & abscissae () const inline
Return quadrature abscissae.
Return primary quadrature abscissae.
Definition at line 79 of file univariateMomentSetI.H.
void invert ()
Invert the set of moments to compute weights and abscissae.
Definition at line 70 of file univariateMomentSet.C.
References eigenSolver::eigenvaluesRe(), and eigenSolver::eigenvectors().
Referenced by extendedMomentInversion::invert(), univariateQuadratureApproximation::updateBoundaryQuadrature(), and univariateQuadratureApproximation::updateQuadrature().
void update ()
Update moments from weights and abscissae.
Definition at line 360 of file univariateMomentSet.C.
bool isInverted () const inline
Returns the status of inversion.
Definition at line 27 of file univariateMomentSetI.H.
bool isRealizable () inline
Return realizability status of the moment set.
Definition at line 32 of file univariateMomentSetI.H.
Foam::label nInvertibleMoments () inline
Return the number of invertible moments.
Definition at line 42 of file univariateMomentSetI.H.
Foam::label nRealizableMoments () inline
Return the number of realizable moments.
Definition at line 52 of file univariateMomentSetI.H.
Referenced by extendedMomentInversion::invert(), gammaEQMOM::m2N(), lognormalEQMOM::m2N(), and lognormalEQMOM::sigmaMax().
Foam::label nMoments () const inline
Return the number of moments.
Definition at line 62 of file univariateMomentSetI.H.
Foam::label nNodes () const inline
Return the number of nodes.
Definition at line 67 of file univariateMomentSetI.H.
const Foam::scalarDiagonalMatrix & weights () const inline
Return quadrature weights.
Return primary quadrature weights.
Definition at line 73 of file univariateMomentSetI.H.
The documentation for this class was generated from the following files:
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/univariateMomentSet/univariateMomentSet.H
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/univariateMomentSet/univariateMomentSet.C
/home/alberto/OpenFOAM-dev/albertop-dev/applications/development/OpenQBMM-dev/OpenQBMM-dev/src/quadratureMethods/univariateMomentSet/univariateMomentSetI.H