#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

runApplication blockMesh
cp -r 0.org 0

#runApplication $application
runApplication $application

runApplication reconstructPar

# ----------------------------------------------------------------- end-of-file
