#!/bin/bash
#
createEpsAlpha()
{

    gnuplot<<EOF
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "OpenQBMM_validation_case5_alpha.eps"
    set xlabel "X-Position (m)"
    set ylabel "Volume fraction"
    set grid
    set key right top
    set size 2,2
    set autoscale
    set xrange [0:1]

    plot    "$1" using 1:2 title 'MD(Galvin et. al. 2007)'\
                with lines linewidth 3 linecolor rgb 'black',\
            "$2" using 1:2 title 'Passalacqua et. al. 2011'\
                with lines dt 2 linewidth 2 linecolor rgb 'black',\
            "$3" using 1:3 every 5 title 'OpenQBMM'\
                with points pointtype 5 ps 2 linecolor rgb '#9db668'
EOF
}

createEpsT()
{

    gnuplot<<EOF
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "OpenQBMM_validation_case5_T.eps"
    set xlabel "X-Position (m)"
    set ylabel "Temperature (m^2/s^2)"
    set grid
    set key right bottom
    set size 2,2
    set autoscale
    set xrange [0:1]

    plot    "$1" using 1:2 title 'MD(Galvin et. al. 2007)'\
                with lines linewidth 3 linecolor rgb 'black',\
            "$2" using 1:2 title 'Passalacqua et. al. 2011'\
                with lines dt 2 linewidth 2 linecolor rgb 'black',\
            "$3" using 1:2 every 5 title 'OpenQBMM'\
                with points pointtype 5 ps 2 linecolor rgb '#9db668'
EOF
}

createEpsQ()
{

    gnuplot<<EOF
    set terminal postscript eps enhanced color font 'Helvetica,40' linewidth 2\
        dl 8.0
    set output "OpenQBMM_validation_case5_heatFlux.eps"
    set xlabel "X-Position (m)"
    set ylabel "Heat flux"
    set grid
    set key right bottom
    set size 2,2
    set autoscale
    set xrange [0:1]

    plot    "$3" using 1:(0.5*(\$6 + \$7 + \$8 + \$3*(\$4/\$3)**3) - (\$4/\$3)*(\$5 + \$3*\$2)) every 5 title 'OpenQBMM'\
                with points pointtype 5 ps 2 linecolor rgb '#9db668',\
            "$1" using 1:2 title 'MD(Galvin et. al. 2007)'\
                with lines linewidth 3 linecolor rgb 'black',\
            "$2" using 1:2 title 'Passalacqua et. al. 2011'\
                with lines dt 2 linewidth 2 linecolor rgb 'black'
EOF
}

# test if gnuplot exists on the system
if ! which gnuplot > /dev/null 2>&1
then
    echo "gnuplot not found - skipping graph creation" >&2
    exit 1
fi

# paths to data
VALIDATIONDATAROOT=./validationData
time=$(cd ../ && foamListTimes -latestTime)

TP_alpha="$VALIDATIONDATAROOT/case5_alpha_TP.csv"
MD_alpha="$VALIDATIONDATAROOT/case5_alpha_MD.csv"
TP_T="$VALIDATIONDATAROOT/case5_T_TP.csv"
MD_T="$VALIDATIONDATAROOT/case5_T_MD.csv"
# TP_Q="$VALIDATIONDATAROOT/case5_Q_TP.csv"
# MD_Q="$VALIDATIONDATAROOT/case5_Q_MD.csv"
OPENQBMM="../postProcessing/sampleDict/$time/Centerline*"

createEpsAlpha $MD_alpha $TP_alpha $OPENQBMM
createEpsT $MD_T $TP_T $OPENQBMM
# createEpsQ $MD_Q $TP_Q $OPENQBMM

echo Done
