#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mkdir 0 2>&1
cp 0.org/* 0/ 2>&1

cp -f system/controlDict.flow system/controlDict
runApplication blockMesh
runApplication buoyantSimpleFoam

mv 100000 100000.flow
cp -f 100000.flow/* 0/ 2>&1
cp -f system/controlDict.pbe system/controlDict

runApplication decomposePar -time 0
runParallel pbeTransportFoam 4

runApplication reconstructPar -latestTime

# ----------------------------------------------------------------- end-of-file
