#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../AllrunFunctions

mkdir 0 2>&1
cp 0.orig/* 0/ 2>&1

cp -f system/controlDict.flow system/controlDict 2>&1
runStep blockMesh
runStep buoyantSimpleFoam

mv 50000 50000.flow 2>&1
cp -f 50000.flow/* 0/ 2>&1
cp -f system/controlDict.pbe system/controlDict 2>&1

runStep decomposePar -time '0'
runStepParallel pbeTransportFoam

runStep reconstructPar -latestTime

# ----------------------------------------------------------------- end-of-file
