#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
. ../../../../AllrunFunctions
application=`getApplication`

runStep blockMesh
runStep generateMoments
runStep $application
runStep postProcess -func sampleDict -latestTime
( cd validation && ./createGraph )
